const express = require('express')
const bodyParser = require('body-parser')
const cookieSession = require('express-session')
const app = express()
const dotenv = require('dotenv')
const mongoose = require('mongoose')
dotenv.config()
mongoose.connect(process.env.MLAB)
app.set('view engine', 'ejs')
app.set('trust proxy', 1)
app.use(cookieSession({ secret: process.env.SECRET, cookie: { maxAge: 60000 }}))
app.use(bodyParser.urlencoded({ extended: false }))
app.use('/', require('./default'))
app.use('/user', require('./user'))
app.use('/post', require('./post'))
app.listen(process.env.PORT || 80)
